### ISSUE TITLE
Innacurate represantation of hydration added to drink_stats.cfg

### ISSUE THREAD

**Issue by ghost** [BlockyNoob/WaterSkin#2]
custom drinks added on drinks_stats.cfg have they hydration value tooltiped wrong. their thirst are correct.

for every single unit of hydration, six drops are rendered in the tool tip. making it 12x what they should be (like in hunger/health, 1 unit is half of an icon). 

if you drink it, the value is set right on your player data, so the issue is only on the tooltip. seeing no issue in the hud overlay.

i tested it by adding a few drinks with increasing hydration value (1, 2, 4). and seen its effect on the overlay once drunk.

**Comment by BlockyNoob** [comment]
This is because TAN uses a formula to calculate its thirst values vs. just reading flat values from the CFG file.

Super simple fix, will be closed before tomorrow
