### ISSUE TITLE
Issue woth classic bars

### ISSUE THREAD

**Issue by Taknax** [BlockyNoob/WaterSkin#4]
The overlays doesnt work fully and by showing the value by full thirst make an issue too.
ClassicBars and AttributeFix should be considered as compat.
Nice mod. Very Useful.
A little suggestion of mine was a compat to CaliberDrinks. Its not possible because the mod has not TAN Compat. I suggested the modowner an compat between. If he gonna do i would tell you again.
Ty for your work!

**Comment by BlockyNoob** [comment]
Ahh, I seem to be lacking quite a but i terms of mod compat.
I'll look into this, it's right up there with Better Hud compatibility.

**Comment by Taknax** [comment]
I dont even use betterHud but its good to consider. many ppl use it. I use apple skin and core and with this mod its really nice.
